### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by LHPegnolatto** [LHPegnolatto/ava-mobile#1]
<details>
  <summary>Mobile APP tasks</summary>

- [x]  Criar tela de login. - 29/04/20
- [x]  Criar tela de recuperar senha. - 01/04/20
- [x]  Criar validações e rotas para autenticação. 04/05/20
- [ ]  Criar tela de loading.
- [ ]  Rever vídeo do Mayk Brito para tornar responsiva as fontes das telas.
- [ ]  Criar um drawer para navegação.
- [ ]  Criar tema escuro.
- [ ]  Criar tela de perfil do usuário.
- [ ]  Criar menu com opção de matérias por turma.
- [ ]  Criar tela de matéria.
- [ ]  Criar tela de conteúdo da semana.
- [ ]  Criar tela de Caixa de Entrada.
- [ ]  Criar tela de calendário.
- [ ]  Criar tela de anotações to-do.
</details>

---

<details>
  <summary>API simulation for AVA issues</summary>

- [x]  Criar diagrama do banco de dados. -05/05/20
- [x]  Criar o banco de dados com migrations utilizando o Knex. - 04/05/20
- [x]  Criar registro de usuários. - 04/05/20
- [x]  Fazer autenticação de login com JWT.
</details>

---

<details>
  <summary>Design issues</summary>

- [x]  Criar logo para o APP. - 06/05/20
- [x]  Fazer uma tela de splash. - 06/05/20
- [x]  Fazer um ícone para o APP. - 06/05/20
</details>
